In [1]:
# import packages and show the contents of npz files
import numpy as np
datadir = 'D:/LHAASO_KM2A/LHAASO/Data/Simulation/Xishui/'
test = np.load(datadir+'rec.all.Proton.1.e14_1.e15.40_70.QGSII_flukacern.root.weighted.npz')
lst=test.files
for item in lst:
    print(item)
    print(test[item])
    

array1 = test['E']
array2 = test['id']
print(len(array1))
print(len(array2))

E
[618628.44 260521.34 118893.89 ... 267890.25 362725.72 306236.94]
id
[14 14 14 ... 14 14 14]
theta
[1.0109657  0.9371906  0.8346488  ... 0.87412107 0.79731554 0.8425322 ]
phi
[2.2208087 1.7232567 3.9435902 ... 4.9795637 4.5471706 4.268569 ]
rec_theta
[1.0139171  1.0040874  0.8212636  ... 0.8686161  0.8039528  0.77929896]
rec_phi
[2.2220607 1.7209753 3.9324944 ... 4.9879875 4.545839  4.23548  ]
corex
[ -90.73377   -22.332224 -145.20836  ...  180.2824   -524.9035
   87.708725]
corey
[ 539.7039   545.4952   557.298   ...  670.47894 -238.53299 -726.5699 ]
rec_x
[ -89.68152   -17.059244 -146.53413  ...  211.71599  -530.5122
  129.07274 ]
rec_y
[ 537.0704   552.43964  545.29456 ...  601.12946 -238.93105 -454.1259 ]
pNpE
[927  98  54 ...  88 221  39]
pNuM
[126  32  15 ...  23  40  26]
NhitE
[506 170 127 ... 175 242 127]
NhitM
[196 142 113 ... 122 132 119]
NfiltE
[199  54  31 ...  30  80  10]
NfiltM
[44 15  8 ... 10 16  8]
NpE1
[1300.513     111.63752    79.38474  ...   27.7107    232.69868


In [2]:
# Read proton files
import glob
npzfiles = glob.glob(datadir + 'rec.all.Proton*.npz')
for i, npzfile in enumerate(npzfiles):
    if i==0:
        test = np.load(npzfile, allow_pickle=True)
        arr1 = test['E']
        arr2 = test['theta']
        arr3 = test['NhitE']

    else:
        f = np.load(npzfile, allow_pickle=True)
        ene = f['E']
        theta = f['theta']
        hitE = f['NhitE']
        arr1 = np.append(arr1, ene)
        arr2 = np.append(arr2, theta)
        arr3 = np.append(arr3, hitE) 
pri_features = np.column_stack((arr1, arr2,arr3))
pri_features


array([[5.47173779e+03, 3.05945903e-01, 9.90000000e+01],
       [8.59261133e+03, 2.14569256e-01, 1.04000000e+02],
       [7.23614844e+03, 3.15549344e-01, 1.01000000e+02],
       ...,
       [1.01228060e+07, 1.53692234e+00, 1.25000000e+02],
       [2.79591080e+07, 1.50963235e+00, 1.06000000e+02],
       [8.27407360e+07, 1.51517344e+00, 1.15000000e+02]])

In [3]:
# read iron files
npzfiles = glob.glob(datadir + 'rec.all.Fe*.npz')
for i, npzfile in enumerate(npzfiles):
    if i==0:
        test = np.load(npzfile, allow_pickle=True)
        arr11 = test['E']
        arr22 = test['theta']
        arr33 = test['NhitE']

    else:
        f = np.load(npzfile, allow_pickle=True)
        ene = f['E']
        theta = f['theta']
        hitE = f['NhitE']
        arr11 = np.append(arr11, ene)
        arr22 = np.append(arr22, theta)
        arr33 = np.append(arr33, hitE) 
features1 = np.column_stack((arr11, arr22,arr33))
features1

array([[3.19880312e+04, 4.40464437e-01, 1.15000000e+02],
       [3.56524922e+04, 2.91274101e-01, 1.07000000e+02],
       [5.04254961e+04, 2.48385459e-01, 1.48000000e+02],
       ...,
       [8.06034960e+07, 1.53035557e+00, 1.31000000e+02],
       [8.06034960e+07, 1.53035557e+00, 1.33000000e+02],
       [2.34836820e+07, 1.53493893e+00, 1.35000000e+02]])